"""initial schema

Revision ID: 26ee841d18ba
Revises: 
Create Date: 2026-09-17 10:58:42.318886+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '26ee841d18ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('root_cause', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('affected_resources', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('potentially_affected', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('on_chain', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('recommendation', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('rule_set_version', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.ARRAY(sa.Text()), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_diagnosis_confidence'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_created_at'), 'diagnosis', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnosis_root_cause'), 'diagnosis', ['root_cause'], unique=False)
    op.create_table('ingest_batch',
    sa.Column('batch_id', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('vm_id', sa.Text(), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_resources', sa.Integer(), nullable=False),
    sa.Column('accepted_events', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index('ix_batch_received', 'ingest_batch', ['received_at'], unique=False)
    op.create_index(op.f('ix_ingest_batch_agent_id'), 'ingest_batch', ['agent_id'], unique=False)
    op.create_index(op.f('ix_ingest_batch_vm_id'), 'ingest_batch', ['vm_id'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('observability', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.CheckConstraint("kind IN ('host', 'gpu', 'vgpu', 'vm', 'container', 'process', 'ai_service', 'agent', 'task', 'unresolved')", name='ck_resource_kind'),
    sa.CheckConstraint("observability IN ('active','stale','gone')", name='ck_resource_observability'),
    sa.CheckConstraint("status IN ('running','stopped','error','unknown')", name='ck_resource_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['resource.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_kind'), 'resource', ['kind'], unique=False)
    op.create_index('ix_resource_kind_observability', 'resource', ['kind', 'observability'], unique=False)
    op.create_index(op.f('ix_resource_last_seen_at'), 'resource', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_resource_observability'), 'resource', ['observability'], unique=False)
    op.create_index(op.f('ix_resource_parent_id'), 'resource', ['parent_id'], unique=False)
    op.create_index(op.f('ix_resource_status'), 'resource', ['status'], unique=False)
    op.create_table('alert',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('first_fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('evidence_event_ids', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('aggregation_key', sa.String(length=256), nullable=False),
    sa.Column('diagnosis_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.CheckConstraint("severity IN ('info','warning','error','critical')", name='ck_alert_severity'),
    sa.CheckConstraint("state IN ('firing','acked','resolved','silenced')", name='ck_alert_state'),
    sa.CheckConstraint('coalesce(array_length(evidence_event_ids, 1), 0) >= 1', name='ck_alert_evidence_required'),
    sa.CheckConstraint('count >= 1', name='ck_alert_count_positive'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_aggregation_active', 'alert', ['aggregation_key', 'state'], unique=False)
    op.create_index(op.f('ix_alert_aggregation_key'), 'alert', ['aggregation_key'], unique=False)
    op.create_index(op.f('ix_alert_diagnosis_id'), 'alert', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_alert_last_fired_at'), 'alert', ['last_fired_at'], unique=False)
    op.create_index(op.f('ix_alert_resource_id'), 'alert', ['resource_id'], unique=False)
    op.create_index(op.f('ix_alert_rule_id'), 'alert', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_severity'), 'alert', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_state'), 'alert', ['state'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("severity IN ('info','warning','error','critical')", name='ck_event_severity'),
    sa.CheckConstraint("source IN ('zsvirt','probe','derived')", name='ck_event_source'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_batch_id'), 'event', ['batch_id'], unique=False)
    op.create_index(op.f('ix_event_occurred_at'), 'event', ['occurred_at'], unique=False)
    op.create_index('ix_event_occurred_id', 'event', ['occurred_at', 'id'], unique=False)
    op.create_index(op.f('ix_event_resource_id'), 'event', ['resource_id'], unique=False)
    op.create_index('ix_event_resource_occurred', 'event', ['resource_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_event_severity'), 'event', ['severity'], unique=False)
    op.create_index(op.f('ix_event_trace_id'), 'event', ['trace_id'], unique=False)
    op.create_index(op.f('ix_event_type'), 'event', ['type'], unique=False)
    op.create_index('ix_event_type_occurred', 'event', ['type', 'occurred_at'], unique=False)
    op.create_table('resource_edge',
    sa.Column('parent_id', sa.Text(), nullable=False),
    sa.Column('child_id', sa.Text(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('parent_id <> child_id', name='ck_edge_no_self_loop'),
    sa.ForeignKeyConstraint(['child_id'], ['resource.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_index('ix_edge_child', 'resource_edge', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edge_child', table_name='resource_edge')
    op.drop_table('resource_edge')
    op.drop_index('ix_event_type_occurred', table_name='event')
    op.drop_index(op.f('ix_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_trace_id'), table_name='event')
    op.drop_index(op.f('ix_event_severity'), table_name='event')
    op.drop_index('ix_event_resource_occurred', table_name='event')
    op.drop_index(op.f('ix_event_resource_id'), table_name='event')
    op.drop_index('ix_event_occurred_id', table_name='event')
    op.drop_index(op.f('ix_event_occurred_at'), table_name='event')
    op.drop_index(op.f('ix_event_batch_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_alert_state'), table_name='alert')
    op.drop_index(op.f('ix_alert_severity'), table_name='alert')
    op.drop_index(op.f('ix_alert_rule_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_resource_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_last_fired_at'), table_name='alert')
    op.drop_index(op.f('ix_alert_diagnosis_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_aggregation_key'), table_name='alert')
    op.drop_index('ix_alert_aggregation_active', table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_resource_status'), table_name='resource')
    op.drop_index(op.f('ix_resource_parent_id'), table_name='resource')
    op.drop_index(op.f('ix_resource_observability'), table_name='resource')
    op.drop_index(op.f('ix_resource_last_seen_at'), table_name='resource')
    op.drop_index('ix_resource_kind_observability', table_name='resource')
    op.drop_index(op.f('ix_resource_kind'), table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_ingest_batch_vm_id'), table_name='ingest_batch')
    op.drop_index(op.f('ix_ingest_batch_agent_id'), table_name='ingest_batch')
    op.drop_index('ix_batch_received', table_name='ingest_batch')
    op.drop_table('ingest_batch')
    op.drop_index(op.f('ix_diagnosis_root_cause'), table_name='diagnosis')
    op.drop_index(op.f('ix_diagnosis_created_at'), table_name='diagnosis')
    op.drop_table('diagnosis')
    # ### end Alembic commands ###
